Main:
	g++ MyException.cpp main.cpp -o .\build\main
	.\build\main

DisparoExcepcion1:
	g++ DisparoExcepcion1.cpp -o .\build\DisparoExcepcion1
	.\build\DisparoExcepcion1

DisparoExcepcion2:
	g++ DisparoExcepcion2.cpp -o .\build\DisparoExcepcion2
	.\build\DisparoExcepcion2

DisparoExcepcion3:
	g++ DisparoExcepcion3.cpp -o .\build\DisparoExcepcion3
	.\build\DisparoExcepcion3

.PHONY: clean

clean:
	rm .\build\*