TestBubbleSort:
	g++ sourceSort.cpp TestBubbleSort.cpp -o .\build\TestBubbleSort
	.\build\TestBubbleSort

TestSelectionSort:
	g++ sourceSort.cpp TestSelectionSort.cpp -o .\build\TestSelectionSort
	.\build\TestSelectionSort

TestInsertionSort:
	g++ sourceSort.cpp TestInsertionSort.cpp -o .\build\TestInsertionSort
	.\build\TestInsertionSort

TestQuickSort:
	g++ sourceSort.cpp TestQuickSort.cpp -o .\build\TestQuickSort
	.\build\TestQuickSort

.PHONY: clean

clean:
	rm .\build\*